### ISSUE TITLE
Missing pip when installing SnowCLI

### ISSUE THREAD

**Issue by sfc-gh-mharding** [Snowflake-Labs/homebrew-snowcli#7]
brew install snowcli

...
==> Installing snowcli from snowflake-labs/snowcli
==> python3 -m venv --without-pip /usr/local/Cellar/snowcli/1.0.1/libexec
==> /usr/local/Cellar/snowcli/1.0.1/libexec/bin/python -m pip install pip==22.3.1
Last 15 lines from /Users/mharding/Library/Logs/Homebrew/snowcli/02.python:
2023-08-30 15:51:23 +0000

/usr/local/Cellar/snowcli/1.0.1/libexec/bin/python
-m
pip
install
pip==22.3.1

/usr/local/Cellar/snowcli/1.0.1/libexec/bin/python: No module named pip

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/snowflake-labs/homebrew-snowcli/issues

**Comment by sfc-gh-puneet-lakhanpal** [comment]
I came across the same issue too

**Comment by sfc-gh-pjob** [comment]
Hello, I was able to reproduce the error on my machine.

It turns out that homebrew 4.1.4 changed changed the behaviour of the function responsible for creating python virtual environment and now pip is no longer available by default (https://github.com/Homebrew/brew/pull/15792). I've updated our formula to use the old behaviour and now it seems to work correctly (I've tested it on my machine and snowcli has installed correctly).

Please remember to use `brew update` to update snowcli's tap formula before retrying to install.

It's possible that our formula won't work anymore for homebrew older than 4.1.4. In that case, we suggest to update homebrew.
